### ISSUE TITLE
Use traefik to expose the web frontend

### ISSUE THREAD

**Issue by ctgraham** [Caligula1022/ccvg_integral#2]
To make the Docker deployment entirely self contained, good practice is to use a container which publicly presents ports 80 and 443.

Please add a [traefik container](https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/) to expose ports 80 and 443, mapping to the frontend's web port.

The selection of an SSL certificate for port 443 should be part of the environment configuration.

**Comment by Caligula1022** [comment]
I added a traefik container, please check if it is correct.

**Comment by ctgraham** [comment]
The existing compose file exposes ports and endpoints useful for development:
https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L9
https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L18
https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L26
https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L51
https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L58
From a production deployment, the only exposed ports and names should be that of the frontend (angular app) on 80 and 443.  We'll want to remove the other ports and names for production purposes.  A common way to do this is to maintain a docker compose file dedicated to development and a compose file which is dedicated to production.

We will also want to migrate the traefik hostname to be an environment variable:
https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L43

This will allow you to configure the name as `angular.docker.localhost` for your development purposes, but for a production configuration we would add an actual DNS name in place as the environment variable.

Finally, the current traefik configuration does bring up the site on port 80 (HTTP) but does not map port 443 (HTTPS) to the angular container.  You can leave the SSL certificate as the self-signed certificate for your development purposes; good practice would be to also allow traefik to mount an SSL certificate installed on the docker host via an environment variable.

**Comment by ctgraham** [comment]
Moved to https://github.com/ulsdevteam/ccvgd-integral/issues/2
